defaults:
  - /data: point_cloud
  - /model: pointnet
  - /task: diurnality_binary
  - /split: species
  - /training: default
  - _self_

statistics:
  stats_output_file: results/${task.output}/${data.type}/${model.type}/${split.type}_split/run_{run}/stats.csv
  predictions_output_file: results/${task.output}/${data.type}/${model.type}/${split.type}_split/run_{run}/predictions.csv

runs: 5