data:
  copies: 5
  transformations:
    - name: center
      parameters: {}
    - name: random_rotation
      parameters: {}
    - name: reshape
      parameters:
        shape: [3, 200] # reshape the point cloud 

  split:
    type: species
    seed: 
    train_ratio: 0.8

  task:
    input: x # x denotes the point cloud
    output: diurnality

model:
  type: pointnet_pp_cls
  num_classes: 3
  sa_layers:
    - type: msg
      npoint: 200
      radius_list: [6, 12, 18]
      nsample_list: [16, 32, 64]
      pos: true
      normals: 0
      mlp_list: [[32, 32, 64], [64, 64, 128], [64, 96, 128]]
    - type: msg
      npoint: 130
      radius_list: [6, 12, 18]
      nsample_list: [12, 18, 24]
      pos: true
      normals: 320
      mlp_list: [[64, 64, 128], [128, 128, 256], [128, 128, 256]]
    - type: vanilla
      npoint: 130
      radius: !!float inf # infinity, this means that all points will be grouped together
      nsample: !!float inf
      pos: true
      normals: 640
      mlp_list: [256, 512, 1024]
  mlp_layers:
  - in_channel: 1024
    out_channel: 512
    bn: true
    dropout: 0.4
  - in_channel: 512
    out_channel: 256
    bn: true
    dropout: 0.5
  - in_channel: 256
    out_channel: 3 # this should be equal to num_classes

training:
  gpu: true
  optimizer:
    type: adam
    learning_rate: 0.001
  loss: cross_entropy
  scheduler:
    type: plateau
    scheduler_step_size: 10
    scheduler_gamma: 0.1  
  batch_size: 100 #100
  epochs: 2



